dist: xenial
language: go

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+.*$/
  - /^release-\d+.\d+.*$/

git:
  depth: false

jobs:
  include:
  - env: CMD="make test validate codegen"
  - env: CMD="make e2e"
         RELEASE=true

install:
  - sudo apt-get install moreutils # make ts available
  - sudo add-apt-repository -y ppa:wireguard/wireguard # add WireGuard support
  - sudo apt-get update
  - sudo apt-get install wireguard -y

services:
  - docker
before_script:
  - CHANGED_FILES_PR=$(git diff --name-only HEAD $(git merge-base HEAD $TRAVIS_BRANCH))
script:
  - set -o pipefail;
    $CMD 2>&1 | ts '[%H:%M:%.S]' -s
after_success:
    echo "Testing cleaning up clusters";
    set -o pipefail;
    make cleanup 2>&1 | ts '[%H:%M:%.S]' -s
deploy:
  - provider: script
    script: make images images_flags="--nocache" release release_images="submariner submariner-route-agent submariner-globalnet"
    on:
      branch: master
      condition: $RELEASE = true
  - provider: script
    script: make images images_flags="--nocache" release release_images="submariner submariner-route-agent submariner-globalnet"
    on:
      branch: /^release-\d+.\d+.*$/

  - provider: script
    script: make images images_flags="--nocache" release release_images="submariner submariner-route-agent submariner-globalnet" release_tag="$TRAVIS_TAG"
    skip_cleanup: true
    on:
      tags: true
      condition: $RELEASE = true
