dist: xenial
language: go

git:
  depth: 1

before_script:
  - CHANGED_FILES=$(git diff --name-only HEAD $(git merge-base HEAD $TRAVIS_BRANCH))

script:
  - echo "test"

after_success:
  - if [[ "${CHANGED_FILES[@]}" =~ "scripts/kind-e2e/e2e.sh" ]]; then
      echo "scripts/kind-e2e/e2e.sh was modified, testing again on already deployed environment.";
      make e2e status=keep;
    fi
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"