dist: xenial
language: go

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+.*$/
  - /^release-\d+.\d+.*$/
  - /^z_pr.*$/

git:
  depth: false

jobs:
  include:
  - env: CMD="make test validate"
  - env: CMD="make build package e2e status=keep deploytool=operator" DEPLOY=true
  - env: CMD="make build package e2e status=keep deploytool=helm globalnet=true"

install:
  - sudo apt-get install moreutils # make ts available
services:
  - docker
before_script:
  - CHANGED_FILES_PR=$(git diff --name-only HEAD $(git merge-base HEAD $TRAVIS_BRANCH))
script:
  - set -o pipefail;
    $CMD 2>&1 | ts '[%H:%M:%.S]' -s
after_success:
  - if [[ $CMD =~ "e2e" &&
          ( "${CHANGED_FILES_PR[@]}" =~ "scripts/kind-e2e/e2e.sh" ) ||
          ( $CMD =~ "helm" && "${CHANGED_FILES_PR[@]}" =~ "scripts/kind-e2e/lib_helm_deploy_subm.sh" ) ||
          ( ! $CMD =~ "helm" && "${CHANGED_FILES_PR[@]}" =~ "scripts/kind-e2e/lib_operator_deploy_subm.sh" ) ]]; then
      echo "scripts/kind-e2e/*.sh files used by this job were modified, testing recurring run on already deployed infrastructure.";
      set -o pipefail;
      $CMD 2>&1 |  ts '[%H:%M:%.S]' -s;
    fi;
    echo "Testing cleaning up clusters";
    set -o pipefail;
    make e2e status=clean 2>&1 | ts '[%H:%M:%.S]' -s
deploy:
  - provider: script
    script: bash scripts/release
    on:
      branch: master
      condition: $DEPLOY = true
  - provider: script
    script: bash scripts/release
    on:
      branch: /^release-\d+.\d+.*$/

  - provider: script
    script: bash scripts/release $TRAVIS_TAG
    skip_cleanup: true
    on:
      tags: true
      condition: $DEPLOY = true
