# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: submariner:ipam
rules:
- apiGroups:
  - ""
  resources:
  - services
  - namespaces
  - pods
  verbs:
  - list
  - watch
  - get
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: submariner:ipam
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: submariner:ipam
subjects:
- kind: ServiceAccount
  name: submariner-ipam
  namespace: submariner
