---
name: External Network Tests

on:
  pull_request:

jobs:
  e2e-external:
    name: External Network E2E
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        globalnet: ['', 'globalnet']
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run E2E deployment and tests
        uses: submariner-io/shipyard/gh-actions/e2e@devel
        with:
          plugin: '/go/src/github.com/submariner-io/submariner/scripts/e2e/external/hook'
          testdir: 'test/external'
          using: ${{ matrix.globalnet }}
