on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v**'

name: End to End Tests
jobs:
  e2e:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        globalnet: ['', '--globalnet']
        deploytool: ['operator', 'helm']
        cable_driver: ['', 'wireguard', 'libreswan']
        exclude:
# Our Helm setup doesn’t know how to deploy other cable drivers
          - deploytool: 'helm'
            cable_driver: 'wireguard'
          - deploytool: 'helm'
            cable_driver: 'libreswan'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Install WireGuard module (On WireGuard tests)
        if: matrix.cable_driver == 'wireguard'
        run: |
          sudo add-apt-repository -y ppa:wireguard/wireguard # add WireGuard support
          sudo apt-get update
          sudo apt-get install  linux-headers-$(uname -r) wireguard  -y
          # temporary solution for Ubuntu 16.04 azure-1020
          sudo curl -Lk https://git.zx2c4.com/wireguard-linux/plain/drivers/net/wireguard/queueing.h\?id\=428c491332bca498c8eb2127669af51506c346c7  -o /usr/src/wireguard-1.0.20200506/queueing.h
          sudo dpkg-reconfigure wireguard-dkms

          sudo modprobe wireguard

      - name: Reclaim free space!
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h
          free -h

      - name: Run E2E deployment and tests
        env:
          CLUSTERS_ARGS: ${{ matrix.globalnet }}
          DEPLOY_ARGS: ${{ matrix.globalnet }} --deploytool ${{ matrix.deploytool }}
        run: |
          [[ -z "${{ matrix.cable_driver }}" ]] || DEPLOY_ARGS+=" --deploytool_submariner_args '--cable-driver ${{ matrix.cable_driver }}'"
          make e2e

      - name: Post Mortem
        if: failure()
        run: |
          df -h
          free -h
          make post-mortem
