---
name: Linting

on:
  pull_request:
  push:
    tags:
      - 'v**'

jobs:
  code-gen:
    name: Submariner K8s API Code Generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Run validation
        run: make codegen

  dco:
    runs-on: ubuntu-latest
    name: DCO in Commit Message(s)
    steps:
      - name: Get PR Commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: DCO Check
        uses: tim-actions/dco@master
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}

  gitlint:
    name: Commit Message(s)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - run: make gitlint

  markdown-link-check:
    name: Markdown Links (modified files)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Run markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: ".markdownlinkcheck.json"
          check-modified-files-only: "yes"

  validate:
    name: Go and Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Run golangci-lint
        run: make validate

  yaml-lint:
    name: YAML
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v1
        with:
          file_or_dir: .
          config_file: .yamllint.yml
