---
name: Release Images

on:
  push:
    branches:
      - devel
      - release-*

jobs:
  release:
    name: Release Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@25a956c84d5dd820d28caab9f86b8d183aeeff3d
        with:
          fetch-depth: 0

      - name: Build and release new images
        uses: submariner-io/shipyard/gh-actions/release-images@devel
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
